fix: add nakama-debug on docker-compose to fix debug mode
Argus-Labs/starter-game-template pull request #51
Opened 2024-06-12 09:01 UTC by zulkhair

2024-06-12 09:01 UTC, zulkhair commented
* **#51** <a href="https://app.graphite.dev/github/pr/Argus-Labs/starter-game-template/51?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @zulkhair and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-13 16:47 UTC, rmrt1n reviewed
what if we use two docker compose files, e.g. `docker-compose.dev.yaml` and `docker-compose.prod.yaml`, instead of putting all containers here? The dev compose file contains the debug containers, and it'll be run only in dev or with the `--debug` world CLI flag.

2024-06-14 04:08 UTC, smsunarto requested changes
Instead of adding `nakama-debug`, a trick here is to just pass in the depends_on container name using environment variable https://stackoverflow.com/questions/29377853/how-can-i-use-environment-variables-in-docker-compose

If the `--debug` flag in the CLI is used, inject an environment variable that would change the depended container name to `cardinal-debug`, otherwise it would use the default value `cardinal`

2024-06-19 15:29 UTC, zulkhair commented
> Instead of adding `nakama-debug`, a trick here is to just pass in the depends_on container name using environment variable https://stackoverflow.com/questions/29377853/how-can-i-use-environment-variables-in-docker-compose
> 
> If the `--debug` flag in the CLI is used, inject an environment variable that would change the depended container name to `cardinal-debug`, otherwise it would use the default value `cardinal`
> 
> 

Tried this but error. 
```
validating /home/daim/Documents/Argus/repo/starter-game-template/docker-compose.yml: services.nakama.depends_on Additional property ${DOCKER_CARDINAL_SERVICE_NAME:-cardinal} is not allowed
Error: Encountered an error with Docker: exit status 15
```

I will try to find another solutions.

2024-06-20 10:11 UTC, zulkhair commented
> what if we use two docker compose files, e.g. `docker-compose.dev.yaml` and `docker-compose.prod.yaml`, instead of putting all containers here? The dev compose file contains the debug containers, and it'll be run only in dev or with the `--debug` world CLI flag.

Updated using two docker-compose file. 
CLI will run with args `-f docker-compose.yml -f docker-compose.debug.yml up` in `--debug` mode and it will override the first docker-compose file with the second one.

2024-06-20 17:38 UTC, smsunarto commented
The whole goal is to reduce the number of duplication. If you are creating a separate docker compose then you end up with even more duplication

2024-06-20 19:00 UTC, rmrt1n commented
> Updated using two docker-compose file. CLI will run with args `-f docker-compose.yml -f docker-compose.debug.yml up` in `--debug` mode and it will override the first docker-compose file with the second one.

this follows [docker compose's extend](https://docs.docker.com/compose/multiple-compose-files/extends/) rules. ([summary of rules here](https://stackoverflow.com/a/67734078)).

it's a bit error-prone if you don't know how the override works on different options, but imo it's an ok approach to this, similar to a plugin system. you just include it for debug mode.

setting `depends_on` using env vars probably doesn't work with the [long form](https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1), but it could in the short form. I couldn't get this to work tho :shrug:.

probably we can try using [compose profiles](https://docs.docker.com/compose/profiles/)? run the debug containers when in the `dev`/`debug` profile, and the regular ones in `prod` profile. then we just have to change the commands in world-cli depending on the debug flag: `docker compose --profile debug up`.

2024-06-20 19:14 UTC, smsunarto commented
You can do 

```
    depends_on:
      - "${NAME_OF_ENV_VAR_GOES_HERE:-default-value-goes-here}"
 ```

2024-06-20 19:46 UTC, zulkhair commented
> You can do
> 
> ```
>     depends_on:
>       - "${NAME_OF_ENV_VAR_GOES_HERE:-default-value-goes-here}"
> ```
> 
> Note the "" quotation marks around it

Updated to short syntax, it works but need to remove the condition specifies that a dependency is expected to be "healthy" `condition: service_healthy` for nakama-db

2024-06-20 23:22 UTC, smsunarto commented
You can overwrite the entrypoint/cmd in docker compose for the Nakama service. Just make it run `curl -s --fail -- --connect-timeout 1 --retry 10 <cockroachdb healthcheck API> && <original entrypoint commands>` 

CockroachdB healthcheck API: https://www.cockroachlabs.com/docs/api/cluster/v2.html#operation/health

with retries: https://stackoverflow.com/questions/42873285/curl-retry-mechanism

2024-06-21 12:48 UTC, zulkhair commented
> You can overwrite the entrypoint/cmd in docker compose for the Nakama service to run the healthcheck from within the container.
> 
> Just make it run `curl -s --fail --connect-timeout 1 --retry 10 <cockroachdb healthcheck API> && <original entrypoint commands>`
> 
> CockroachdB healthcheck API: https://www.cockroachlabs.com/docs/api/cluster/v2.html#operation/health
> 
> with retries: https://stackoverflow.com/questions/42873285/curl-retry-mechanism

After i'm testing it, i think we don't need to do health check for nakama-db, using sort syntax should be enough.

I tried to run docker compose without nakama-db, nakama will automatically retry to run `migrate up` from entrypoint for the db until success, so it can be used as healtcheck.

2024-06-21 20:38 UTC, smsunarto approved these changes

2024-06-21 20:38 UTC, merged